### ISSUE TITLE
[Bug] The radon aquarium glass block and the infernal one do not render correctly with embeddium

### ISSUE THREAD

**Issue by EvilWarriorZ** [VoidArkana/Fintastic#1]
I am using the last version of Fintastic and rubidium
![image](https://github.com/user-attachments/assets/9fddea0e-fe65-48ae-8947-1baacd6ec215)

**Comment by EvilWarriorZ** [comment]
The same seems to happen with the sugar glass

**Comment by VoidArkana** [comment]
I can't do anything on my end, unfortunately, because of the way Embeddium changes the minecraft code
